#ifndef FASTQ_CONTROL_SAMPLER_H
#define FASTQ_CONTROL_SAMPLER_H

	////////////////////////////////////////////////////////////////////////
	//  STRUCTURES
	////////////////////////////////////////////////////////////////////////

	// Structure 
	typedef struct info T_info;
	struct info
	{
		char* name;
		int size_name;
		char* seq;
		int size_seq;
		int nb_seq;
		T_info* next;
	};

	////////////////////////////////////////////////////////////////////////
	//  GLOBAL VARIABLES
	////////////////////////////////////////////////////////////////////////

	// If 1 = pairs will not be chosen in repeat region identified by lowercase characteres
	int MASK_REPEAT = 1;
	// Size of the read to be generated
	int SIZE_READ = 150;
	// Minimal size of fragments generated by fragmentation at the end of the experimental protocol
	int SIZE_MIN_SONIC = 200;
	// Maximal size of fragments generated by fragmentation at the end of the experimental protocol
	int SIZE_MAX_SONIC = 600;
	// Size of the random reference sequence generated during the first step of the program 
	int SIZE_OF_RANDOM_REF = 100000;
	// Maximum number of tries to generate a valid read pair ie : sufficiant size and without 'N' in it
	int MAX_TRY_VALID_PAIR = 100;
	// Nunber of pairs to be generated for the randon ref
	int NB_PAIRS = 100;
	// Frequency of errors in reads
	double ERR_FREQ = 0.01;
	// Minimal PHRED Quality score in fastq sequences
	int MIN_QUAL = 30;
	// Maximal PHRED Quality score in fastq sequences
	int MAX_QUAL = 40;
	// if TRUE fasta files will also be genereted
	int FASTA = 0;
	// Counter of mutations added in fastq sequences
	int MUTATION = 0;
	// DNA bases
	const char DNA_BASES [] =  "ACTGatcg";
	// ################################################################################
	// for now only illumina quality score >= 1.8 are suported

	////////////////////////////////////////////////////////////////////////
	//  PROTOTYPES
	////////////////////////////////////////////////////////////////////////

	void usage (char*);
	T_info* create_ref_list (char**, int, int);
	void print_list (T_info*);
	void generate_fastq (T_info*);
	char reverse_seq (char);
	char forward_seq (char);
	char* generate_random_ref (int);
	int nref (FILE*);
	T_info* create_info_cell(void);
	int evaluate_name_size (FILE*);
	int evaluate_seq_size (FILE*);
	char* output_name (FILE*, int);
	char* output_seq (FILE*, int);
	int select_read_pair (T_info* ptri, char**, char**);
	void generate_random_quality (char**, char**);

#endif /* FASTQ_CONTROL_SAMPLER_H */
